<?php

require_once __DIR__ . '/vendor/autoload.php';

use \GuzzleHttp\Client;
use \Sylius\Api\Client as SyliusClient;
use \Sylius\Api\Map\ArrayUriMap;
use \Sylius\Api\ApiResolver;
use \CommerceGuys\Guzzle\Oauth2\GrantType\RefreshToken;
use \CommerceGuys\Guzzle\Oauth2\GrantType\PasswordCredentials;
use \CommerceGuys\Guzzle\Oauth2\Oauth2Subscriber;

$oauth2Client = new Client([
    'base_url' => 'http://local.sylius.dev/app_dev.php/',
]);

$config = [
    'token_url' => 'oauth/v2/token',
    'client_id' => '1_demo_client',
    'client_secret' => 'secret_demo_client',
    'username' => 'api@example.com',
    'password' => 'api'
];

$token = new PasswordCredentials($oauth2Client, $config);
$refreshToken = new RefreshToken($oauth2Client, $config);

$oauth2 = new Oauth2Subscriber($token, $refreshToken);

$client = new Client([
    'base_url' => 'http://local.sylius.dev/app_dev.php/api/',
    'defaults' => [
        'auth' => 'oauth2',
        'subscribers' => [$oauth2],
    ],
]);

// create sylius client
$syliusClient = new SyliusClient($client);

$syliusClient = SyliusClient::createFromUrl('http://local.sylius.dev/app_dev.php/api/', $oauth2);

// initialize uri mapping for custom uris, all other uris are autogenerated (plural name of the resource, in accordance with RESTful API resource naming best practices)
$uriMap = new ArrayUriMap(
    [
        'product-variants' => 'products/{productId}/variants',
        'taxons'           => 'taxonomies/{taxonomyId}/taxons',
        'items'            => 'orders/{orderId}/items',
        'coupons'          => 'promotions/{promotionId}/coupons',
        'provinces'        => 'countries/{countryId}/provinces'
    ]
);
// initializer api resolver
$apiResolver = new ApiResolver($syliusClient, $uriMap);
